### PR TITLE
More descriptive output for the update_index.py script

### PR DESCRIPTION
**Pull request by gnikonorov**
`update_index.py` may take some time to run, so I felt more descriptive script output would be useful. I added the following:
- print statements for every action taken
- progress bars for actions that loop over iterables, since these take some time to run and there's currently no visual indication for how far along in the process we are.

For the progress bar I used [tqdm](https://github.com/tqdm/tqdm), as it seems active enough and is simple to use ( just wrap an iterable in `tqdm( )` )

I attached a screenshot showing the output of the script with these changes. It's still terse, but descriptive enough IMO so that users know where they are at all times, as can be seen below:

Screen Shot 2020-11-21 at 8 02 25 PM

### CODE REVIEW

**Comment by gnikonorov** [comment]
Bump for a review @nicoddemus

**Review by nicoddemus — APPROVED** [review]
Thanks!

**Comment by gnikonorov** [comment]
@nicoddemus am I ok to just merge these on my own once you approve and all checks pass or should we not merge our own PRs in this repo?

**Comment by nicoddemus** [comment]
> @nicoddemus am I ok to just merge these on my own once you approve and all checks pass or should we not merge our own PRs in this repo?

It is fine to merge them yourself after approval and checks passed, I didn't do it in a timely manner because Travis was taking too long so I went to do other things and it ended up slipping my mind. 😊

**Comment by nicoddemus** [comment]
Thanks again!

**Comment by gnikonorov** [comment]
> It is fine to merge them yourself after approval and checks passed, I didn't do it in a timely manner because Travis was taking too long so I went to do other things and it ended up slipping my mind. 😊

Of course, thank you for confirming!

**Pull request merged**
