### PR TITLE
add some test coverage for run.py

### PR DESCRIPTION
**Pull request by wimglenn**

### CODE REVIEW

**Comment by wimglenn** [comment]
Do you think we can remove the execution of `run.py` from PR builder, now that it has good test coverage?

**Comment by nicoddemus** [comment]
But I think it makes sense to execute `run.py` on PRs, because we might start doing PRs for changes in `run.py` itself. To make sure I'm not missing something, why do you want to skip `run.py` from PRs?

**Comment by wimglenn** [comment]
I guess it's just the philosophy of it: You know it works in the current state. And PRs for changes in `run.py` itself should include test coverage for whatever they're changing. So to actually execute it in the PR is a waste of time/resources, or it indicates you're not confident about the test coverage.

**Comment by nicoddemus** [comment]
Oh sorry about that, I misunderstood you, when you said "remove the execution of run.py" I thought you meant the *tests* for `run.py`. My bad!

You got a point, but on the other hand the actual execution of `run.py` is a couple of minutes in the common case (when most packages will be skipped because they already have test results for the current version). TBH I don't mind much either way. 😁

**Pull request merged**
