### PR TITLE
bdist_wheel

### PR DESCRIPTION
**Pull request by wimglenn**
display fewer false negatives onsite for plugin maintainers who wish to distribute wheels and not sdist

closes https://github.com/pytest-dev/plugincompat/issues/25

### CODE REVIEW

**Comment by wimglenn** [comment]
Yes, I suggested something similar in my comment [here](https://github.com/pytest-dev/plugincompat/pull/29#issuecomment-416766929).  That's a little different (slightly hacky), but the same idea - it would seem simpler because then you don't need to conditionally apply a limit depending on whether you're running in master or on PR.

**Comment by nicoddemus** [comment]
> I suggested something similar in my earlier comment here. 

Oh my bad, I must have missed this.

> I could refactor to make it work, but tbh my preference is not to execute run.py on PR at all.

Let's go with your preference then, no problem. 😁

**Comment by wimglenn** [comment]
@nicoddemus   There's one manual step after this change.  Results which were marked as "NO SOURCE" will need to be invalidated (probably just deleted in db) otherwise they will be skipped and will not be reconsidered until a new version is published.

**Comment by nicoddemus** [comment]
OK, I just did that and restarted the jobs, thanks for the ping. 👍

**Comment by nicoddemus** [comment]
Oh didn't notice on the review 😅

**Pull request merged**
